using UnityEngine;

namespace CreateAR.SpirePlayer
{
    /// <summary>
    /// Configuration for all widgets.
    /// </summary>
    public class WidgetConfig : MonoBehaviour
    {
        /// <summary>
        /// Multiplier for auto-generated buffer colliders.
        /// </summary>
        public float AutoGeneratedWidgetBufferColliderSize = 1.5f;

        /// <summary>
        /// Multiplies aim fill.
        /// </summary>
        public AnimationCurve AimFillMultiplier = new AnimationCurve(
            new Keyframe(0, 1),
            new Keyframe(1, 4));

        /// <summary>
        /// Multiplies steadiness fill.
        /// </summary>
        public AnimationCurve SteadinessFillMultiplier = new AnimationCurve(
            new Keyframe(0, 1),
            new Keyframe(1, 4));

        /// <summary>
        /// Duration for full fillm in seconds.
        /// </summary>
        public float FillDuration = 2.0f;

        /// <summary>
        /// Fill decay multiplier.
        /// </summary>
        public AnimationCurve FillDecay = AnimationCurve.EaseInOut(0, 1, 1, 0);
    }
}