//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Projects\Work\commons\commons-unity-vine\Vine\VineParser.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Vine {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IVineParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public partial class VineParserBaseListener : IVineParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocument([NotNull] VineParser.DocumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocument([NotNull] VineParser.DocumentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] VineParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] VineParser.ElementContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContent([NotNull] VineParser.ContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContent([NotNull] VineParser.ContentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.misc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMisc([NotNull] VineParser.MiscContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.misc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMisc([NotNull] VineParser.MiscContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] VineParser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] VineParser.CommentContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScript([NotNull] VineParser.ScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScript([NotNull] VineParser.ScriptContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] VineParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] VineParser.AttributeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.attributeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributeName([NotNull] VineParser.AttributeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.attributeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributeName([NotNull] VineParser.AttributeNameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.attributeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttributeValue([NotNull] VineParser.AttributeValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.attributeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttributeValue([NotNull] VineParser.AttributeValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Vine
