//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VineParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="VineParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IVineParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocument([NotNull] VineParser.DocumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocument([NotNull] VineParser.DocumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement([NotNull] VineParser.ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement([NotNull] VineParser.ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContent([NotNull] VineParser.ContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContent([NotNull] VineParser.ContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.misc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMisc([NotNull] VineParser.MiscContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.misc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMisc([NotNull] VineParser.MiscContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] VineParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] VineParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] VineParser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] VineParser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] VineParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] VineParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.attributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeName([NotNull] VineParser.AttributeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.attributeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeName([NotNull] VineParser.AttributeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VineParser.attributeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeValue([NotNull] VineParser.AttributeValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VineParser.attributeValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeValue([NotNull] VineParser.AttributeValueContext context);
}
